# Desarrollo de CNN 

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Librerias para las CNN
import torch 
import torch.nn as nn # Cargamos esto para la red neuronal
import torch.optim as optim 

In [3]:
# Visualizar del dataset con numpy
dataset = np.loadtxt("../data/pima-indians-diabetes.csv", delimiter=',')
print(dataset)

[[  6. 148.  72. ... 627.  50.   1.]
 [  1.  85.  66. ... 351.  31.   0.]
 [  8. 183.  64. ... 672.  32.   1.]
 ...
 [  5. 121.  72. ... 245.  30.   0.]
 [  1. 126.  60. ... 349.  47.   1.]
 [  1.  93.  70. ... 315.  23.   0.]]


In [4]:
# Definimos las caracteristicas
X = dataset[:, 0:8]
print("x")
print(X)

# Target
y = dataset[:,8]
print("y")
print(y[0:10])

x
[[  6.  148.   72.  ...  33.6 627.   50. ]
 [  1.   85.   66.  ...  26.6 351.   31. ]
 [  8.  183.   64.  ...  23.3 672.   32. ]
 ...
 [  5.  121.   72.  ...  26.2 245.   30. ]
 [  1.  126.   60.  ...  30.1 349.   47. ]
 [  1.   93.   70.  ...  30.4 315.   23. ]]
y
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1.]


Para continuar, debemos convertir los datos de la siguiente maneta:
- X en un tensor, debido a que numpy maneja los valores en 64 bits, mientras Pythorch lo hace en 32.
- Convertir y en una matriz de 1 columna

In [5]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).reshape(-1,1)
print("x\n", X)
print("y\n", y)

x
 tensor([[  6.0000, 148.0000,  72.0000,  ...,  33.6000, 627.0000,  50.0000],
        [  1.0000,  85.0000,  66.0000,  ...,  26.6000, 351.0000,  31.0000],
        [  8.0000, 183.0000,  64.0000,  ...,  23.3000, 672.0000,  32.0000],
        ...,
        [  5.0000, 121.0000,  72.0000,  ...,  26.2000, 245.0000,  30.0000],
        [  1.0000, 126.0000,  60.0000,  ...,  30.1000, 349.0000,  47.0000],
        [  1.0000,  93.0000,  70.0000,  ...,  30.4000, 315.0000,  23.0000]])
y
 tensor([[1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

## Definimos nuestro modelo

In [6]:
'''
Modelo tradicional, pero también el menos común en entonos de trabajo

model = nn.Sequential(
    nn.Linear(8, 12),
    nn.ReLU(),
    nn.Linear(12, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
    nn.Sigmoid()
)
print(model)

'''

'\nModelo tradicional, pero también el menos común en entonos de trabajo\n\nmodel = nn.Sequential(\n    nn.Linear(8, 12),\n    nn.ReLU(),\n    nn.Linear(12, 8),\n    nn.ReLU(),\n    nn.Linear(8, 1),\n    nn.Sigmoid()\n)\nprint(model)\n\n'

In [8]:
# En forma de Clase
class PrimaCalssifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden1 = nn.Linear(8, 12)
        self.act1 = nn.ReLU()
        self.hidden2 = nn.Linear(12, 8)
        self.act2 = nn.ReLU()
        self.output = nn.Linear(8, 1)
        self.act_output = nn.Sigmoid

    def forward(self, x):
        x = self.act1(self.hidden1, (x))
        x = self.act2(self.hidden2, (x))
        x = self.act_output(self.output, (x))
        return(x)
    

model = PrimaCalssifier()
        

In [9]:
print(model)

PrimaCalssifier(
  (hidden1): Linear(in_features=8, out_features=12, bias=True)
  (act1): ReLU()
  (hidden2): Linear(in_features=12, out_features=8, bias=True)
  (act2): ReLU()
  (output): Linear(in_features=8, out_features=1, bias=True)
)


## Pereparación para el entrenamiento

In [12]:
loss_fn = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)